<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon />
    <AssemblyName>VisualControlServer</AssemblyName>
    <RootNamespace>VisualControl.Server</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\VisualControl.Shared.csproj" />
  </ItemGroup>
</Project>
